### ISSUE TITLE
Error: package-tap.i18n should be loaded before languages files (*.i18n.json)

### ISSUE THREAD

**Issue by surtic86** [TAPevents/tap-i18n#169]
I have updated from 1.8.0 to 1.8.1 and now get following Error and can't get ride of it. Any Idea whats wrong? Meteor Version is 1.3.2.4

Thanks for your help.

`W20160524-13:44:14.933(2)? (STDERR)
W20160524-13:44:14.934(2)? (STDERR) /Users/surtic86/.meteor/packages/meteor-tool/.1.3.2_4.r6dp5x++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160524-13:44:14.934(2)? (STDERR) 						throw(ex);
W20160524-13:44:14.934(2)? (STDERR) 						      ^
W20160524-13:44:14.990(2)? (STDERR) Error: package-tap.i18n should be loaded before languages files (*.i18n.json)
W20160524-13:44:14.990(2)? (STDERR)     at _ (home/theosp/tap-i18n/unittest/test-packages/blank-package-tap-i18n/package-tap.i18n:1:1)
W20160524-13:44:14.990(2)? (STDERR)     at home/theosp/tap-i18n/unittest/test-packages/blank-package-tap-i18n/package-tap.i18n:1:1
W20160524-13:44:14.990(2)? (STDERR)     at packages/tap_i18n/packages/tap_i18nunittest/test-packages/project-with-translation-files-under-server-dir-SHOULD-FAIL/server/file2.en.i18n.json:12:1
W20160524-13:44:14.990(2)? (STDERR)     at /Users/surtic86/Privat/Development/Meteor/EasyTranslate/.meteor/local/build/programs/server/boot.js:283:10
W20160524-13:44:14.991(2)? (STDERR)     at Array.forEach (native)
W20160524-13:44:14.991(2)? (STDERR)     at Function._.each._.forEach (/Users/surtic86/.meteor/packages/meteor-tool/.1.3.2_4.r6dp5x++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160524-13:44:14.991(2)? (STDERR)     at /Users/surtic86/Privat/Development/Meteor/EasyTranslate/.meteor/local/build/programs/server/boot.js:133:5`

**Comment by poltorak** [comment]
+1 I'm facing the same issue

**Comment by theosp** [comment]
Hi guys,

Sorry about that, revert temporarily to 1.8.0.

I will fix it in the following hours.

-Daniel

**Comment by theosp** [comment]
I need your help finding the cause as I don't have yet any project built with v1.3:

Please pull the repository to your packages directory and let me know whether the issue persist when checking out the following commits (please try all of them):

8fa3cf51968e8beb031737ecf92db17a2d49f955 (v1.8.1 - part 2)

ae3cb2a487cca0926e512a0450d9ea95956e52fd (v1.8.1 - part 1)

6ce3f166f0eba89407b29be47033d29587d82394 (v1.8)

Thanks,
-Daniel

**Comment by krishaamer** [comment]
Same here. App crashing with Error: package-tap.i18n should be loaded before languages files (*.i18n.json) after upgrade

**Comment by davidecantini** [comment]
Same error here, it was working on 1.8.0.

**Comment by jerms** [comment]
Same error with Meteor 1.3.2.4.

Isn't it due to the nunittest folders in the package ? In the version 1.8.0, there was no folder "home" or "package".

> (STDERR) at _ (home/theosp/tap-i18n/unittest/test-packages/blank-package-tap-i18n/package-tap.i18n:1:1) W20160524-13:44:14.990(2)? 
> (STDERR) at home/theosp/tap-i18n/unittest/test-packages/blank-package-tap-i18n/package-tap.i18n:1:1

It looks like the package 1.8.1 was not done in the same way than the previous one.

**Comment by MartinBucko** [comment]
+1 
same here with versions  1.8.1 and 1.8.0 and Meteor 1.3.2.4

**Comment by theosp** [comment]
@jerms Probably the issue, I guess that the `$ meteor publish` command itself got changed.

I removed the unittest folder completely and published v1.8.2, let me know if it helps, if it doesn't we'll try other things.

Please LMK if the issue persist in v1.8.2 .

Thanks,
-Daniel

**Comment by surtic86** [comment]
@theosp: Yes it works again with 1.8.2

**Comment by theosp** [comment]
Great!

**Comment by jerms** [comment]
Hey, it's working again with 1.8.2. ;)
Thanks Daniel.

**Comment by issachan** [comment]
Unfortunately, I'm still getting this error. I have v 1.8.2. 

I'm using a droplet on Digital Ocean
Ubuntu 16.04.1 x64

Could anyone assist?

**Comment by theosp** [comment]
I suspect that it's very likely to be connected with: https://github.com/meteor/meteor/issues/7842 - try the workaround suggested there: try putting package files under a folder that starts with '.#' example: '.#unwatched' and update your package.js with the new path.

Let me know if it helped, I hope will be solved by Meteor v1.4.2 https://github.com/meteor/meteor/pull/7668#issuecomment-250947793 .

**Comment by c9s** [comment]
1.8.2 doesn't work with 1.4.1.1

**Comment by theosp** [comment]
@c9s did you try the '.#unwatched' workaround?

**Comment by c9s** [comment]
I saw it, but I don't know which file to ignore.

could you describe more about this? thank you.

Daniel C <notifications@github.com> 於 2016年10月6日 星期四寫道：

**Comment by c9s** [comment]
I think the unittest folder should be renamed to "tests", and this will solve this issue.

but another issue will show up:

```
.meteor/packages/templating-compiler/.1.2.15.dxsyei++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:177
      throw error;
      ^

Error: isopack mdg:validation-error not yet loaded?
    at Error (native)
    at IsopackCache.getIsopack (/tools/isobuild/isopack-cache.js:111:13)
    at Object.compiler.eachUsedUnibuild (/tools/isobuild/compiler.js:927:36)
    at JsImageTarget.<anonymous> (/tools/isobuild/bundler.js:807:18)
    at Object.compiler.eachUsedUnibuild (/tools/isobuild/compiler.js:955:5)
```

**Comment by issachan** [comment]
Thanks, but no luck with this. I still cannot get past the language file issue.

**Comment by c9s** [comment]
same here. meteor really sucks

Issa Chan <notifications@github.com> 於 2016年10月11日 星期二寫道：

**Comment by llvasconcellos** [comment]
@c9s I have the same problem: Error: isopack mdg:validation-error not yet loaded?
Did you manage to solve it?

**Comment by c9s** [comment]
I downgraded to 1.5.2, the 1.8.2 totally sucks

Leonardo Lima de Vasconcellos <notifications@github.com> 於 2016年10月19日
星期三寫道：

**Comment by llvasconcellos** [comment]
@theosp Where is version 1.8.2. I forked the repo and want to add some changes but master branch is 1.8.1

**Comment by quape** [comment]
so there is no working version of this package with current meteor version??

**Comment by llvasconcellos** [comment]
I just gave up on meteor.

**Comment by quape** [comment]
so what instead?
I love Meteor but so many things are just stupid together with old docs and things that just don't work anymore :(

**Comment by c9s** [comment]
The messy package system wasted my whole week to fix it and got no result

Sad

quape <notifications@github.com>於 2017年1月24日 週二，19:46寫道：

**Comment by derwaldgeist** [comment]
Ran in the same issue when upgrading my app from 1.2 to 1.3. Is there any solution for this?

**Comment by Pagebakers** [comment]
Remove this file: .meteor/local/resolver-result-cache.json and run again :)

**Comment by derwaldgeist** [comment]
I solved it by removing all package-tap.i18n files. They're not working anyways, so it did not make sense to keep them. Unfortunately, this package is quite poorly maintained. After upgrading to Meteor 1.5, I had to take out all i18n files from my packages, since tap:i18n did not work if the ecmascript package was activated in them. Weird. Solved this by moving all i18n files in their own packages and excluded ecmascript there.

**Comment by FrancisBou** [comment]
Getting this error as well, very unclear how to resolve this issue.

**Comment by derwaldgeist** [comment]
That's what I did:
- get rid of all package-tap.i18n (didn't work anymore anyways)
- moved all i18n files to separate packages (like myapp-home-i18n) and omitted ecmascript in them

**Comment by evolross** [comment]
I just upgraded an app on Meteor 1.8.1 to the latest "aldeed" packages that are the npm  `simpl-schema@1.5.6`, `aldeed:collection2@3.0.6`, `aldeed:autoform@6.3.0`. Was previously on the very old set of packages where `aldeed:simple-schema` was a Meteor package.

Went about updating `tap:i18n` because of its `aldeed:simple-schema@1.3.0` dependency and how that _could_ conflict with the npm `simpl-schema` according to its docs and I'm seeing some weirdness in `aldeed:autoform@6.3.0` with nested schema error validations and messages. So I tried updating to some of the forked packages that been updated to depend on npm `simpl-schema` versus `aldeed:simple-schema`. I immediately got this error on building my app.  After much Googling and experimentation, removing the packages `unittest` made it work.  On to debugging `aldeed:autoform@6.3.0`.

But `tap:i18n` just seems wrecked at this point.  Switching to npm `i18next` looks _involved_ as does [universe:i18n](https://github.com/vazco/meteor-universe-i18n).  Looks like [ostrio:i18n](https://github.com/VeliovGroup/Meteor-Internationalization/) could be a relatively pain free replacement - as it comes with similar Blaze template helpers even allowing you to update their `i18n` helper to `tap:i18n`'s `_` helper.

**Comment by derwaldgeist** [comment]
I can recommend `universe:i18n`, it worked reliably. Haven't tried the ostrio package, though.
