### ISSUE TITLE
while I am running meteor project I got this error -> [SyntaxError: Unexpected end of JSON input]

### ISSUE THREAD

**Issue by SagarOps** [TAPevents/tap-i18n#224]
```
C:\Users\MM\AppData\Local\.meteor\packages\tap_i18n\1.8.2\plugin.tap-i18n-compiler.os\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
      ^

[SyntaxError: Unexpected end of JSON input
  at JSON.parse (<anonymous>:null:null)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\fs\optimistic.js:384:17
  at wrap.makeCacheKey (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\fs\optimistic.js:114:15)
  at recomputeNewValue (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:245:35)
  at Slot.withValue (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@wry\context\lib\context.js:73:29)
  at reallyRecompute (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:231:21)
  at Entry.recompute (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:158:15)
  at optimistic (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:465:27)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\fs\optimistic.js:415:19
  at recomputeNewValue (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:245:35)
  at Slot.withValue (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@wry\context\lib\context.js:73:29)
  at reallyRecompute (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:231:21)
  at Entry.recompute (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:158:15)
  at optimistic (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\optimism\lib\bundle.cjs.js:465:27)
  at find (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1365:32)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1407:29
  at Array.forEach (<anonymous>:null:null)
  at find (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1388:24)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1407:29
  at Array.forEach (<anonymous>:null:null)
  at find (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1388:24)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1407:29
  at Array.forEach (<anonymous>:null:null)
  at find (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1388:24)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1407:29
  at Array.forEach (<anonymous>:null:null)
  at find (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1388:24)
  at find (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1421:27)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1436:36
  at Object.withCache (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\fs\files.js:1671:18)
  at PackageSource._findSources (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1436:20)
  at SourceArch.getFiles (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\package-source.js:1023:34)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\compiler.js:434:71
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\compiler.js:211:30
  at Object.withCache (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\fs\files.js:1671:18)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\compiler.js:210:13
  at Function._.each._.forEach (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\underscore\underscore.js:186:9)
  at Object.compile (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\compiler.js:205:7)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\bundler.js:3099:26
  at Object.capture (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\utils\buildmessage.js:284:5)
  at bundle (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\bundler.js:3055:33)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\bundler.js:3006:34
  at Slot.withValue (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@wry\context\lib\context.js:73:29)
  at Object.withCache (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\fs\files.js:1671:39)
  at Object.bundle (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\isobuild\bundler.js:3006:18)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\runners\run-app.js:588:24
  at Function.run (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\tool-env\profile.js:280:14)
  at bundleApp (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\runners\run-app.js:587:34)
  at AppRunner._runOnce (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\runners\run-app.js:634:35)
  at AppRunner._fiber (C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\runners\run-app.js:976:28)
  at C:\Users\MM\AppData\Local\.meteor\packages\meteor-tool\2.2.4\mt-os.windows.x86_64\tools\runners\run-app.js:421:12
]
```

**Comment by evolross** [comment]
Again, package long abandoned. Use a more updated fork.

**Comment by Sagar-Shah33** [comment]
Thanks for replying at the earliest.
Do you mean that the package called 'tap_i18n' is deprecated and no longer can work?
Would be more helpful, If you can give a step-by-step solution to overcome these issues.

**Comment by evolross** [comment]
The package still works. We still use it. Though it's _very_ outdated and uses a lot of packages that are deprecated. What you need to do is look at the [forks network](https://github.com/TAPevents/tap-i18n/network) and look at which one has been updated to work with the latest Meteor. It looks like [this one](https://github.com/w4pnemsak/tap-i18n) is the latest and most updated. You'll then need to clone that into your `packages` folder and run it as a local package (search the Meteor forums about this).
