### ISSUE TITLE
Meteor 1.1.0.2 TypeError: Property 'extend' of object #<Object>

### ISSUE THREAD

**Issue by kainlite** [TAPevents/tap-i18n#71]
Hi,

Im trying to get tap:i18n on a simple project but I keep getting this:

``` 
W20150507-20:58:14.614(-3)? (STDERR) ~/.meteor/packages/meteor-tool/.1.1.3.j3dwdo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150507-20:58:14.614(-3)? (STDERR)                                            throw(ex);
W20150507-20:58:14.614(-3)? (STDERR)                                                  ^
W20150507-20:58:14.653(-3)? (STDERR) TypeError: Property 'extend' of object #<Object> is not a function
W20150507-20:58:14.653(-3)? (STDERR)     at Object.init (packages/tap:i18n/lib/tap_i18next/tap_i18next-1.7.3.js:611:1)
W20150507-20:58:14.653(-3)? (STDERR)     at __coffeescriptShare (packages/tap:i18n/lib/tap_i18next/tap_i18next_init.js:1:1)
W20150507-20:58:14.653(-3)? (STDERR)     at ~/Dropbox/Webs/project/.meteor/local/build/programs/server/packages/tap_i18n.js:2817:4
W20150507-20:58:14.653(-3)? (STDERR)     at packages/tap:i18n/lib/tap_i18n/tap_i18n-server.coffee:1:1
W20150507-20:58:14.654(-3)? (STDERR)     at ~/Dropbox/Webs/project/.meteor/local/build/programs/server/boot.js:222:10
W20150507-20:58:14.654(-3)? (STDERR)     at Array.forEach (native)
W20150507-20:58:14.654(-3)? (STDERR)     at Function._.each._.forEach (~/.meteor/packages/meteor-tool/.1.1.3.j3dwdo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150507-20:58:14.654(-3)? (STDERR)     at ~/Dropbox/Webs/project/.meteor/local/build/programs/server/boot.js:117:5

``` 

Couldnt find anything related anywhere, so I'm asking that here.

Thanks for your time :+1:

**Comment by theosp** [comment]
Replicate on an example repo and send to me.

Thanks,
-Daniel [Meteor Developer](http://www.meteorspark.com/)

**Comment by kainlite** [comment]
Seems that I could solve the issue after all, I did a new meteor app, added all packages, wasnt able to replicate the issue, I added even android platform to it, nothing, copied all my code over, nothing, I just replaced the packages file of my app for the one of the new app (same packages, diff order), and the error went away... but I couldnt replicate the error on a brand new app...
